<a href="https://colab.research.google.com/github/rohanwadia/ML---LAB/blob/main/Logistic_Regression_using_sklearn__(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
def normalize(X):

    #function to normalize feature matrix, X

    mins = np.min(X, axis = 0)
    maxs = np.max(X, axis = 0)
    rng = maxs - mins
    norm_X = 1 - ((maxs - X)/rng)
    return norm_X

In [11]:
from sklearn import datasets, linear_model, metrics
import csv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('/content/dataset1 (2).csv')
dataset=np.array(dataset)
X = normalize(dataset[:, :-1])


# stacking columns wth all ones in feature matrix
X = np.hstack((np.matrix(np.ones(X.shape[0])).T, X))
print('\n')
print(X)

# response vector
y = dataset[:, -1]
# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,
                                                    random_state=1)

# create logistic regression object
reg = linear_model.LogisticRegression()

# train the model using the training sets
reg.fit(X_train, y_train)

# making predictions on the testing set
y_pred = reg.predict(X_test)

# comparing actual response values (y_test) with predicted response values (y_pred)
print("Logistic Regression model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)



[[1.         0.19242517 0.05065823]
 [1.         0.41640382 0.09866732]
 [1.         0.6119831  0.17599276]
 [1.         0.69084812 0.29600195]
 [1.         0.6119831  0.27999892]
 [1.         0.68453991 0.35733787]
 [1.         0.74448032 0.44266483]
 [1.         0.73501801 0.33867218]
 [1.         0.90536447 0.4826724 ]
 [1.         0.81071647 0.36800205]
 [1.         0.83911585 0.4640067 ]
 [1.         0.85488637 0.61599492]
 [1.         0.70661863 0.51200227]
 [1.         0.55520926 0.3813289 ]
 [1.         0.44479074 0.25066905]
 [1.         0.25867378 0.11999567]
 [1.         0.19242517 0.01332685]
 [1.         0.         0.        ]
 [1.         0.15142184 0.07732544]
 [1.         0.29653547 0.02932987]
 [1.         0.40694152 0.05333441]
 [1.         0.49211474 0.09600465]
 [1.         0.30284368 0.21866299]
 [1.         0.52996397 0.32266915]
 [1.         0.6687694  0.3920066 ]
 [1.         0.6687694  0.43466331]
 [1.         0.78548365 0.05065823]
 [1.         0.84226996 0.

TypeError: np.matrix is not supported. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

predictions = logmodel.predict(x_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        63
           1       0.95      0.95      0.95        59
           2       0.98      1.00      0.99        55
           3       0.97      0.96      0.96        68
           4       0.97      0.98      0.98        66
           5       0.96      0.90      0.93        52
           6       1.00      1.00      1.00        54
           7       0.98      0.95      0.97        62
           8       0.89      0.98      0.93        51
           9       0.95      0.94      0.94        64

    accuracy                           0.97       594
   macro avg       0.97      0.97      0.97       594
weighted avg       0.97      0.97      0.97       594

[[63  0  0  0  0  0  0  0  0  0]
 [ 0 56  0  0  1  0  0  0  2  0]
 [ 0  0 55  0  0  0  0  0  0  0]
 [ 0  0  0 65  0  0  0  1  2  0]
 [ 0  1  0  0 65  0  0  0  0  0]
 [ 0  1  1  1  0 47  0  0  0  2]
 [ 0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [2]:
from sklearn import datasets, linear_model, metrics

# load the digit dataset
digits = datasets.load_digits()

# defining feature matrix(X) and response vector(y)
X = digits.data
y = digits.target

# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,
                                                    random_state=1)

# create logistic regression object
reg = linear_model.LogisticRegression()

# train the model using the training sets
reg.fit(X_train, y_train)

# making predictions on the testing set
y_pred = reg.predict(X_test)

# comparing actual response values (y_test) with predicted response values (y_pred)
print("Logistic Regression model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

Logistic Regression model accuracy(in %): 96.52294853963839


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

predictions = logmodel.predict(x_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        63
           1       0.95      0.95      0.95        59
           2       0.98      1.00      0.99        55
           3       0.97      0.96      0.96        68
           4       0.97      0.98      0.98        66
           5       0.96      0.90      0.93        52
           6       1.00      1.00      1.00        54
           7       0.98      0.95      0.97        62
           8       0.89      0.98      0.93        51
           9       0.95      0.94      0.94        64

    accuracy                           0.97       594
   macro avg       0.97      0.97      0.97       594
weighted avg       0.97      0.97      0.97       594

[[63  0  0  0  0  0  0  0  0  0]
 [ 0 56  0  0  1  0  0  0  2  0]
 [ 0  0 55  0  0  0  0  0  0  0]
 [ 0  0  0 65  0  0  0  1  2  0]
 [ 0  1  0  0 65  0  0  0  0  0]
 [ 0  1  1  1  0 47  0  0  0  2]
 [ 0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
